downloads_path: "/app/downloads" # Example paths
# wvd_device_path: "C:/YourPath/wvd/your_device_name.wvd"
# cookies_path: "C:/YourPath/Ozivine/cookies/cookies.txt"

credentials:
  10play: deanj.dev@gmail.com:k$j9uAbB6U # Replace with your own credentials
  # tvnz: username:password
