downloads_path: /app/downloads
# wvd_device_path: "C:/YourPath/wvd/your_device_name.wvd"
# cookies_path: "C:/YourPath/Ozivine/cookies/cookies.txt"

credentials:
  10play: username:password # Replace with your own credentials
  # tvnz: username:password
